# Logistic regression

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [3]:
data = pd.DataFrame(
    [("i love spending time with my friends and family", "positive"),
("that was the best meal i've ever had in my life", "positive"),
("i feel so grateful for everything i have in my life", "positive"),
("i received a promotion at work and i couldn't be happier", "positive"),
("watching a beautiful sunset always fills me with joy", "positive"),
("my partner surprised me with a thoughtful gift and it made my day", "positive"),
("i am so proud of my daughter for graduating with honors", "positive"),
("listening to my favorite music always puts me in a good mood", "positive"),
("i love the feeling of accomplishment after completing a challenging task", "positive"),
("i am excited to go on vacation next week", "positive"),
("i feel so overwhelmed with work and responsibilities", "negative"),
("the traffic during my commute is always so frustrating", "negative"),
("i received a parking ticket and it ruined my day", "negative"),
("i got into an argument with my partner and we're not speaking", "negative"),
("i have a headache and i feel terrible", "negative"),
("i received a rejection letter for the job i really wanted", "negative"),
("my car broke down and it's going to be expensive to fix", "negative"),
("i'm feeling sad because i miss my friends who live far away", "negative"),
("i'm frustrated because i can't seem to make progress on my project", "negative"),
("i'm disappointed because my team lost the game", "negative")],
columns= ["text", "sentiment"]
)

In [7]:
data = data.sample(frac=1).reset_index(drop=True)
data

                                                 text sentiment
0   i'm frustrated because i can't seem to make pr...  negative
1   i am so proud of my daughter for graduating wi...  positive
2      i'm disappointed because my team lost the game  negative
3   my car broke down and it's going to be expensi...  negative
4   watching a beautiful sunset always fills me wi...  positive
5   i received a rejection letter for the job i re...  negative
6   i received a promotion at work and i couldn't ...  positive
7   i feel so grateful for everything i have in my...  positive
8   my partner surprised me with a thoughtful gift...  positive
9     that was the best meal i've ever had in my life  positive
10  listening to my favorite music always puts me ...  positive
11  i feel so overwhelmed with work and responsibi...  negative
12  i'm feeling sad because i miss my friends who ...  negative
13  i got into an argument with my partner and we'...  negative
14              i have a headache and i feel terrible  negative
15  i love the feeling of accomplishment after com...  positive
16    i love spending time with my friends and family  positive
17   i received a parking ticket and it ruined my day  negative
18           i am excited to go on vacation next week  positive
19  the traffic during my commute is always so fru...  negative

In [8]:
x = data["text"]
y = data["sentiment"]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
countvec = CountVectorizer()
countvec_fit = countvec.fit_transform(x)
countvec_fit

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 180 stored elements and shape (20, 118)>

In [14]:
bow = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out())
bow

    accomplishment  after  always  am  an  ...  we  week  who  with  work
0                0      0       0   0   0  ...   0     0    0     0     0
1                0      0       0   1   0  ...   0     0    0     1     0
2                0      0       0   0   0  ...   0     0    0     0     0
3                0      0       0   0   0  ...   0     0    0     0     0
4                0      0       1   0   0  ...   0     0    0     1     0
5                0      0       0   0   0  ...   0     0    0     0     0
6                0      0       0   0   0  ...   0     0    0     0     1
7                0      0       0   0   0  ...   0     0    0     0     0
8                0      0       0   0   0  ...   0     0    0     1     0
9                0      0       0   0   0  ...   0     0    0     0     0
10               0      0       1   0   0  ...   0     0    0     0     0
11               0      0       0   0   0  ...   0     0    0     1     1
12               0      0       0   0   0  ...   0     0    1     0     0
13               0      0       0   0   1  ...   1     0    0     1     0
14               0      0       0   0   0  ...   0     0    0     0     0
15               1      1       0   0   0  ...   0     0    0     0     0
16               0      0       0   0   0  ...   0     0    0     1     0
17               0      0       0   0   0  ...   0     0    0     0     0
18               0      0       0   1   0  ...   0     1    0     0     0
19               0      0       1   0   0  ...   0     0    0     0     0

[20 rows x 118 columns]

In [15]:
x_train, x_test, y_train, y_test = train_test_split(bow, y, test_size=0.3 , random_state=7)
# random_state makes sure we have the same train and test split each time we run the code

In [19]:
print(x_train, end="\n\n")
print(x_test)

    accomplishment  after  always  am  an  ...  we  week  who  with  work
18               0      0       0   1   0  ...   0     1    0     0     0
6                0      0       0   0   0  ...   0     0    0     0     1
13               0      0       0   0   1  ...   1     0    0     1     0
19               0      0       1   0   0  ...   0     0    0     0     0
10               0      0       1   0   0  ...   0     0    0     0     0
14               0      0       0   0   0  ...   0     0    0     0     0
8                0      0       0   0   0  ...   0     0    0     1     0
16               0      0       0   0   0  ...   0     0    0     1     0
9                0      0       0   0   0  ...   0     0    0     0     0
12               0      0       0   0   0  ...   0     0    1     0     0
7                0      0       0   0   0  ...   0     0    0     0     0
3                0      0       0   0   0  ...   0     0    0     0     0
4                0      0       1   0   0  ...   0     0    0     1     0
15               1      1       0   0   0  ...   0     0    0     0     0

[14 rows x 118 columns]

    accomplishment  after  always  am  an  ...  we  week  who  with  work
1                0      0       0   1   0  ...   0     0    0     1     0
17               0      0       0   0   0  ...   0     0    0     0     0
2                0      0       0   0   0  ...   0     0    0     0     0
5                0      0       0   0   0  ...   0     0    0     0     0
11               0      0       0   0   0  ...   0     0    0     1     1
0                0      0       0   0   0  ...   0     0    0     0     0

[6 rows x 118 columns]

In [18]:
print(y_train, end="\n\n")
print(y_test)

18    positive
6     positive
13    negative
19    negative
10    positive
14    negative
8     positive
16    positive
9     positive
12    negative
7     positive
3     negative
4     positive
15    positive
Name: sentiment, dtype: str

1     positive
17    negative
2     negative
5     negative
11    negative
0     negative
Name: sentiment, dtype: str

In [20]:
logistic_regression = LogisticRegression(random_state=1).fit(x_train, y_train)

In [ ]:
y_pred_lr = logistic_regression.predict(x_test)

In [ ]:
y_pred_lr

array(['positive', 'positive', 'positive', 'positive', 'positive',
       'positive'], dtype=object)

In [25]:
y_test

1     positive
17    negative
2     negative
5     negative
11    negative
0     negative
Name: sentiment, dtype: str

In [ ]:
accuracy_score(y_pred_lr, y_test)

0.16666666666666666

In [ ]:
print(classification_report(y_test, y_pred_lr, zero_division=0))

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         5
    positive       0.17      1.00      0.29         1

    accuracy                           0.17         6
   macro avg       0.08      0.50      0.14         6
weighted avg       0.03      0.17      0.05         6

# Naive Bayes
A simple classification algorithm that works using probabilities

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
naive_bayes = MultinomialNB().fit(x_train, y_train)

In [33]:
y_pred_nb = naive_bayes.predict(x_test)

In [34]:
accuracy_score(y_pred_nb, y_test)

0.5

In [35]:
print(classification_report(y_test, y_pred_nb, zero_division=0))

              precision    recall  f1-score   support

    negative       1.00      0.40      0.57         5
    positive       0.25      1.00      0.40         1

    accuracy                           0.50         6
   macro avg       0.62      0.70      0.49         6
weighted avg       0.88      0.50      0.54         6

# Linear Support Vector Machine (SVM)
finds the best possible boundary that separates the classes (+, -)

In [36]:
from sklearn.linear_model import SGDClassifier

In [37]:
svm = SGDClassifier().fit(x_train, y_train)

In [38]:
y_pred_svm = svm.predict(x_test)

In [40]:
accuracy_score(y_pred_svm, y_test)

0.16666666666666666