# <h1><b> Text Tagging </b></h1>

### Part Of Speach Tagging (POS)
Labeling each word in a sentence with its grammatical role

In [1]:
import spacy
import pandas as pd

In [2]:
text_data =  open(r"txt_files\pos_tagging.txt", "r")

In [3]:
# load spacy model
nlp = spacy.load("en_core_web_sm") # is a an english core model that is light weight and faster
emma_ja = text_data.read()
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

A spacy document: an object that stores the text along <br>
with all the linguistic information spaCy generates

In [4]:
spacy_doc = nlp(emma_ja) # spaCy documents each word is already tokenized and tagged
spacy_doc

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [5]:
pos_df = pd.DataFrame(columns=["token", "pos_tag"]) # empty dataframe
for token in spacy_doc:
    pos_df = pd.concat([pos_df,
                        pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])],  ignore_index = True) # one roll table using pd.DataFrame.from_records
    # pd.concat joins the row in to the main dataframe

In [6]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [7]:
pos_df_counts = pos_df.groupby(["token", "pos_tag"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)
pos_df_counts.head(10)

    token pos_tag  counts
88     of     ADP      14
54    her    PRON       9
49    had     AUX       9
6     and   CCONJ       8
111   the     DET       8
0       a     DET       6
114    to    PART       5
61     in     ADP       4
120  very     ADV       4
13   been     AUX       4

In [8]:
pos_df_poscounts = pos_df_counts.groupby(["pos_tag"])["token"].count().sort_values(ascending=False)
pos_df_poscounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [9]:
nouns = pos_df_counts[pos_df_counts.pos_tag == "NOUN"][:10]
nouns

         token pos_tag  counts
48   governess    NOUN       3
46      friend    NOUN       3
130      years    NOUN       2
28   daughters    NOUN       2
35        emma    NOUN       2
82      mother    NOUN       2
103    sisters    NOUN       2
1    affection    NOUN       1
11   authority    NOUN       1
32    distress    NOUN       1

### Named Entity Recognition (NER)
Is the process of finding and labeling essential pieces of information in text. <br>
NER uses a combination of rules and machine learning to dicover the entities

In [10]:
from spacy import displacy # visiualization for spacy that alllows us to see entities highlighted directly in the text
from spacy import tokenizer
from IPython.display import HTML, display
import re

In [11]:
nlp_ner = spacy.load("en_core_web_sm") # spacy model

In [12]:
google_text = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."

In [13]:
spacy_doc_ner = nlp_ner(google_text)
spacy_doc_ner

Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [14]:
for word in spacy_doc_ner.ents:
    print(f"{word} : {word.label_} {word.label}") # label with out the underscore (.lable) is a numeric ID od the entity
# while .label_ is a human-readable label

Google : ORG 383
September 4, 1998 : DATE 391
Larry Page : PERSON 380
Sergey Brin : PERSON 380
PhD : WORK_OF_ART 388
Stanford University : ORG 383
California : GPE 384
about 14% : PERCENT 393
56% : PERCENT 393
IPO : ORG 383
2004 : DATE 391
2015 : DATE 391
Google : ORG 383
Alphabet Inc. : ORG 383
Alphabet : ORG 383
Alphabet : ORG 383
Sundar Pichai : PERSON 380
Google : ORG 383
October 24, 2015 : DATE 391
Larry Page : PERSON 380
Alphabet : GPE 384
December 3, 2019 : DATE 391
Pichai : PERSON 380
Alphabet : GPE 384

In [15]:
def html_visiualizer(doc):
    html = displacy.render(doc, style="ent", jupyter=False)
    display(HTML(html))

In [16]:
html_visiualizer(spacy_doc_ner)

In [17]:
google_text_clean = re.sub(r"[^\w\s]", "", google_text).lower()
google_text_clean

'google was founded on september 4 1998 by computer scientists larry page and sergey brin while they were phd students at stanford university in california together they own about 14 of its publicly listed shares and control 56 of its stockholder voting power through supervoting stock the company went public via an initial public offering ipo in 2004 in 2015 google was reorganized as a wholly owned subsidiary of alphabet inc google is alphabets largest subsidiary and is a holding company for alphabets internet properties and interests sundar pichai was appointed ceo of google on october 24 2015 replacing larry page who became the ceo of alphabet on december 3 2019 pichai also became the ceo of alphabet'

In [18]:
spacy_doc_clean = nlp_ner(google_text_clean)

In [19]:
for word in spacy_doc_clean.ents:
    print(f"{word} : {word.label_}")

google : ORG
september 4 1998 : DATE
stanford university : ORG
california : GPE
about 14 : CARDINAL
56 : CARDINAL
2004 : DATE
2015 : DATE
alphabet inc google : ORG
google : ORG
october 24 2015 : DATE
larry : PERSON
december 3 2019 : DATE

In [20]:
html_visiualizer(spacy_doc_clean)