# <h1><b> NLP: TEXT TAGGING PRACTICAL <b><h1>

In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import spacy
import re
import pandas as pd
import matplotlib.pyplot as plt

### Load data

In [2]:
pd.set_option("display.max_colwidth", None)
bbc_df = pd.read_csv(r"txt_files\bbc_news.csv")

In [3]:
bbc_df.head(3)

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?at_medium=RSS&at_campaign=KARANGA,"With much of the UK enduring another period of hot weather, some workers will face very high temperatures."
1,1,9267,'Liz Truss the Brief?' World reacts to UK political turmoil,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_medium=RSS&at_campaign=KARANGA,The UK's political chaos has been watched around the world - and commentators haven't held back.
2,2,7387,Rationing energy is nothing new for off-grid community,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlands-islands-62686916,https://www.bbc.co.uk/news/uk-scotland-highlands-islands-62686916?at_medium=RSS&at_campaign=KARANGA,Scoraig in the north west Highlands has long had to make careful use of its electricity supply.

In [4]:
bbc_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   str
 3   pubDate      1000 non-null   str
 4   guid         1000 non-null   str
 5   link         1000 non-null   str
 6   description  1000 non-null   str
dtypes: int64(2), str(5)
memory usage: 54.8 KB

In [5]:
titles_df = pd.DataFrame(bbc_df["title"])
titles_df.head(10)

                                                                                          title
0                                                                         Can I refuse to work?
1                                   'Liz Truss the Brief?' World reacts to UK political turmoil
2                                        Rationing energy is nothing new for off-grid community
3                                      The hunt for superyachts of sanctioned Russian oligarchs
4                                         Platinum Jubilee: 70 years of the Queen in 70 seconds
5                                      Red Bull found guilty of breaking Formula 1's budget cap
6  World Triathlon Championship Series: Flora Duffy beats Georgia Taylor-Brown to women's title
7                                  Terry Hall: Coventry scooter ride-out pays tribute to singer
8                                  Post Office and Fujitsu to face inquiry over Horizon scandal
9                                                               'Pavement parking frightens me'

### Clean data

In [6]:
# lowercase
titles_df["lowercase"] = titles_df["title"].str.lower()
titles_df.head(3)

,title,lowercase
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK political turmoil,'liz truss the brief?' world reacts to uk political turmoil
2,Rationing energy is nothing new for off-grid community,rationing energy is nothing new for off-grid community

In [7]:
# stop word removal
en_stopwords = stopwords.words("english")
en_stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [8]:
titles_df["rm_stopwords"] = titles_df["lowercase"].apply(lambda data: " ".join([word for word in data.split() if word not in en_stopwords]))
titles_df.head(5)

,title,lowercase,rm_stopwords
0,Can I refuse to work?,can i refuse to work?,refuse work?
1,'Liz Truss the Brief?' World reacts to UK political turmoil,'liz truss the brief?' world reacts to uk political turmoil,'liz truss brief?' world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid community,rationing energy is nothing new for off-grid community,rationing energy nothing new off-grid community
3,The hunt for superyachts of sanctioned Russian oligarchs,the hunt for superyachts of sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 seconds,platinum jubilee: 70 years of the queen in 70 seconds,platinum jubilee: 70 years queen 70 seconds

In [9]:
# punctation removal
titles_df["rm_punctuation"] = titles_df["rm_stopwords"].apply(lambda x: re.sub(r"[^\w\s]", "", x))
titles_df.head(3)

,title,lowercase,rm_stopwords,rm_punctuation
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'Liz Truss the Brief?' World reacts to UK political turmoil,'liz truss the brief?' world reacts to uk political turmoil,'liz truss brief?' world reacts uk political turmoil,liz truss brief world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid community,rationing energy is nothing new for off-grid community,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community

In [10]:
# tokenize
titles_df["token_raw"] = titles_df.apply(lambda x: word_tokenize(x["title"]), axis=1)
titles_df["token_clean"] = titles_df.apply(lambda x: word_tokenize(x["rm_punctuation"]), axis=1)
titles_df.head(3)

,title,lowercase,rm_stopwords,rm_punctuation,token_raw,token_clean
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK political turmoil,'liz truss the brief?' world reacts to uk political turmoil,'liz truss brief?' world reacts uk political turmoil,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts, to, UK, political, turmoil]","[liz, truss, brief, world, reacts, uk, political, turmoil]"
2,Rationing energy is nothing new for off-grid community,rationing energy is nothing new for off-grid community,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off-grid, community]","[rationing, energy, nothing, new, offgrid, community]"

In [11]:
# lemmatizing 
lem = WordNetLemmatizer()
titles_df["lemmatizing"] = titles_df.apply(lambda x: [lem.lemmatize(word) for word in x["token_clean"]], axis=1)
titles_df.head(3)

,title,lowercase,rm_stopwords,rm_punctuation,token_raw,token_clean,lemmatizing
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK political turmoil,'liz truss the brief?' world reacts to uk political turmoil,'liz truss brief?' world reacts uk political turmoil,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts, to, UK, political, turmoil]","[liz, truss, brief, world, reacts, uk, political, turmoil]","[liz, truss, brief, world, reacts, uk, political, turmoil]"
2,Rationing energy is nothing new for off-grid community,rationing energy is nothing new for off-grid community,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off-grid, community]","[rationing, energy, nothing, new, offgrid, community]","[rationing, energy, nothing, new, offgrid, community]"

In [12]:
# create lists for just our tokens
tokens_raw_lst = sum(titles_df["token_raw"], [])
tokens_clean_lst = sum(titles_df["lemmatizing"], [])

In [13]:
tokens_raw_lst

['Can',
 'I',
 'refuse',
 'to',
 'work',
 '?',
 "'Liz",
 'Truss',
 'the',
 'Brief',
 '?',
 "'",
 'World',
 'reacts',
 'to',
 'UK',
 'political',
 'turmoil',
 'Rationing',
 'energy',
 'is',
 'nothing',
 'new',
 'for',
 'off-grid',
 'community',
 'The',
 'hunt',
 'for',
 'superyachts',
 'of',
 'sanctioned',
 'Russian',
 'oligarchs',
 'Platinum',
 'Jubilee',
 ':',
 '70',
 'years',
 'of',
 'the',
 'Queen',
 'in',
 '70',
 'seconds',
 'Red',
 'Bull',
 'found',
 'guilty',
 'of',
 'breaking',
 'Formula',
 '1',
 "'s",
 'budget',
 'cap',
 'World',
 'Triathlon',
 'Championship',
 'Series',
 ':',
 'Flora',
 'Duffy',
 'beats',
 'Georgia',
 'Taylor-Brown',
 'to',
 'women',
 "'s",
 'title',
 'Terry',
 'Hall',
 ':',
 'Coventry',
 'scooter',
 'ride-out',
 'pays',
 'tribute',
 'to',
 'singer',
 'Post',
 'Office',
 'and',
 'Fujitsu',
 'to',
 'face',
 'inquiry',
 'over',
 'Horizon',
 'scandal',
 "'Pavement",
 'parking',
 'frightens',
 'me',
 "'",
 'UK',
 'interest',
 'rates',
 ':',
 'How',
 'will',
 'the',
 'rise',
 'affect',
 'you',
 'and',
 'how',
 'high',
 'could',
 'it',
 'go',
 '?',
 'They',
 'stayed',
 'for',
 'the',
 'storm',
 '-',
 'what',
 'happens',
 'now',
 '?',
 'Six',
 'Nations',
 ':',
 'Can',
 'Scotland',
 "'s",
 'best',
 'since',
 "'99",
 'beat',
 'best',
 'Ireland',
 'ever',
 '?',
 'How',
 'long',
 'can',
 'Liz',
 'Truss',
 'survive',
 'as',
 'prime',
 'minister',
 '?',
 'Platinum',
 'Jubilee',
 ':',
 'Beacons',
 'light',
 'across',
 'the',
 'globe',
 'to',
 'celebrate',
 'Queen',
 "'s",
 'reign',
 'Top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 'by',
 '5',
 '%',
 'in',
 'England',
 'Russians',
 'said',
 'they',
 '’',
 'd',
 'take',
 'my',
 'baby',
 ':',
 'A',
 'medic',
 '’',
 's',
 'story',
 'Week',
 'in',
 'pictures',
 ':',
 '11-17',
 'June',
 '2022',
 'Xi',
 'Jinping',
 'in',
 'Hong',
 'Kong',
 ':',
 'Tight',
 'security',
 'as',
 'city',
 'marks',
 '25',
 'years',
 'of',
 'handover',
 'Rescues',
 'carried',
 'out',
 'in',
 'silence',
 'to',
 'listen',
 'for',
 'sounds',
 'of',
 'life',
 'Nick',
 'Pope',
 ':',
 'Newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'How',
 'China',
 'plans',
 'to',
 'become',
 'the',
 'next',
 'big',
 'space',
 'power',
 'Barcelona',
 'thrash',
 'leaders',
 'Real',
 'Madrid',
 'in',
 'famous',
 'Clasico',
 'win',
 'Kuenssberg',
 ':',
 'The',
 'Budget',
 'can',
 'not',
 'mask',
 'big',
 'changes',
 'to',
 'our',
 'economy',
 'Nicola',
 'Bulley',
 'search',
 ':',
 'What',
 'we',
 'know',
 'about',
 'her',
 'disappearance',
 'Cost',
 'of',
 'living',
 ':',
 'Can',
 'Christmas',
 'lights',
 'displays',
 'survive',
 'the',
 'energy',
 'crisis',
 '?',
 'The',
 '100-year-old',
 'Edinburgh',
 'man',
 'still',
 'working',
 'three',
 'days',
 'a',
 'week',
 'Freya',
 'the',
 '600kg',
 'walrus',
 'causes',
 'a',
 'stir',
 'in',
 'Norway',
 'How',
 'can',
 'I',
 'offer',
 'a',
 'UK',
 'home',
 'to',
 'Ukrainian',
 'refugees',
 '?',
 'Nicola',
 'Bulley',
 'search',
 ':',
 'Former',
 'police',
 'boss',
 'says',
 'criticism',
 'is',
 'unfair',
 'Don',
 'Bolduc',
 ':',
 'Democrats',
 'elevated',
 'this',
 'Republican',
 '.',
 'Will',
 'it',
 'backfire',
 '?',
 'Some',
 'strike',
 'action',
 'cancelled',
 'after',
 'the',
 'Queen',
 "'s",
 'death',
 'The',
 'neighbourhood',
 'leading',
 'a',
 'green',
 'energy',
 'revolution',
 'Men',
 "'s",
 'U17',
 'European',
 'Championship',
 ':',
 'Dutch',
 '17-year-old',
 'Isaac',
 'Babadi',
 'scores',
 'Panenka',
 'penalty',
 'Amtrak',
 'derailment',
 ':',
 'Three',
 'killed',
 'in',
 'Missouri',
 'after',
 'train',
 'hits',
 'truck',
 'Energy',
 'price',
 'cap',
 ':',
 'Rising',
 'bills',
 '-',
 'four',
 'discounts',
 'and',
 'payments',
 'that',
 'could',
 'help',
 'you',
 'Environment',
 ':',
 'Are',
 'mushroom',
 'boards',
 'the',
 'future',
 'of',
 'surfing',
 '?',
 'Flying',
 'boats',
 'and',
 'other',
 'tech',
 'for',
 'cleaner',
 'shipping',
 'Scottish',
 'football',
 'to',
 'ban',
 'heading',
 'the',
 'day',
 'before',
 'and',
 'after',
 'matches',
 'Chris',
 'Eubank',
 'Jr',
 'v',
 'Liam',
 'Smith',
 ':',
 'What',
 'next',
 'for',
 'boxing',
 'after',
 "'unacceptable",
 "'",
 'taunts',
 '?',
 'The',
 'town',
 'destroyed',
 'to',
 'make',
 'way',
 'for',
 'a',
 'whites-only',
 'suburb',
 'Ukraine',
 'war',
 ':',
 'A',
 'village',
 'celebrates',
 'Russian',
 'retreat',
 'Root',
 'hits',
 'ton',
 'as',
 'England',
 'take',
 'command',
 'against',
 'West',
 'Indies',
 'Heineken',
 'Champions',
 'Cup',
 ':',
 'Leicester',
 '16-6',
 'Edinburgh',
 '-',
 'Jasper',
 'Wiese',
 'try',
 'sends',
 'Tigers',
 'into',
 'last',
 'eight',
 'World',
 'Cup',
 '2022',
 ':',
 'Bellingham',
 ',',
 'Gakpo',
 ',',
 'Fernandez',
 'and',
 'other',
 'breakout',
 'stars',
 'Briton',
 'Jack',
 'Fenton',
 'killed',
 'in',
 'Greek',
 'helicopter',
 'accident',
 'Emotional',
 'Sue',
 'Barker',
 'gets',
 'Centre',
 'Court',
 'ovation',
 'Ukrainian',
 'skating',
 'sisters',
 'back',
 'to',
 "'doing",
 'what',
 'they',
 'love',
 "'",
 'England',
 'v',
 'India',
 ':',
 'Edgbaston',
 'officials',
 'investigate',
 'crowd',
 'racism',
 'at',
 'Test',
 'Newspaper',
 'headlines',
 ':',
 'Rwanda',
 'plan',
 "'will",
 'fail',
 "'",
 'and',
 "'SAS",
 'train',
 'Kyiv',
 'forces',
 "'",
 'My',
 'Name',
 'Is',
 'Leon',
 ':',
 'Sir',
 'Lenny',
 'Henry',
 'brings',
 "'moving",
 "'",
 'adoption',
 'story',
 'to',
 'screen',
 'Big',
 'Brother',
 'star',
 'Glyn',
 'Wise',
 'plans',
 'to',
 'be',
 'priest',
 'Ministers',
 'asleep',
 'at',
 'the',
 'wheel',
 'over',
 'dentist',
 'shortages',
 ',',
 'say',
 'Lib',
 'Dems',
 'Chris',
 'Kaba',
 ':',
 'Met',
 'suspends',
 'officer',
 'who',
 'shot',
 'dead',
 'unarmed',
 'man',
 'World',
 'Cup',
 '2022',
 ':',
 'What',
 'we',
 'learned',
 'from',
 'a',
 'group',
 'stage',
 'that',
 'saw',
 'record',
 'number',
 'of',
 'upsets',
 'James',
 'Webb',
 ':',
 'Nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'pictures',
 'Constitution',
 'Hill',
 ':',
 'Cheltenham',
 'Champion',
 'Hurdle',
 'winner',
 "'the",
 'horse',
 'of',
 'a',
 'generation',
 "'",
 'At',
 'least',
 'one',
 'victim',
 'could',
 'have',
 'survived',
 'arena',
 'bomb',
 '-',
 'inquiry',
 'Gareth',
 'Bale',
 ':',
 'Wales',
 'captain',
 'retires',
 'from',
 'football',
 'aged',
 '33',
 'Ukraine',
 'war',
 ':',
 'Silent',
 'streets',
 'in',
 'wiped',
 'out',
 'Donetsk',
 'town',
 'World',
 'Cup',
 '2022',
 ':',
 'Vittorio',
 'Pozzo',
 "'s",
 'legacy',
 'and',
 'a',
 'record',
 'that',
 'might',
 'finally',
 'be',
 'under',
 'threat',
 'Train',
 'strikes',
 ':',
 'Workers',
 'vote',
 'on',
 'further',
 'six',
 'months',
 'of',
 'walkouts',
 'Eidevall',
 "'100",
 '%',
 'sure',
 "'",
 'Arsenal',
 'will',
 'advance',
 'after',
 'first-leg',
 'draw',
 'Ukraine',
 'war',
 ':',
 'Returning',
 'to',
 'the',
 'place',
 'my',
 'father',
 'was',
 'killed',
 'Furniture',
 'firm',
 'Made',
 'collapse',
 ':',
 'Customers',
 'in',
 'the',
 'dark',
 'over',
 'refunds',
 'Widow',
 'of',
 'US',
 'Capitol',
 'riot',
 'officer',
 'on',
 "'stigma",
 "'",
 'of',
 'his',
 'death',
 'NHS',
 'reaches',
 'deal',
 'for',
 'life-saving',
 'breast-cancer',
 'drug',
 'Giant',
 'ceramic',
 'sculpture',
 'by',
 'Sandy',
 'Brown',
 'has',
 'been',
 'unveiled',
 'in',
 'Cornwall',
 'CEO',
 'Secrets',
 ':',
 'How',
 'one',
 'company',
 'attracts',
 'more',
 'men',
 'Boris',
 'Becker',
 ':',
 'How',
 'a',
 'tennis',
 'superstar',
 'crashed',
 'to',
 'earth',
 'Turkish',
 'mine',
 'explosion',
 'kills',
 '25',
 'and',
 'leaves',
 'dozens',
 'trapped',
 'Indian',
 'Wells',
 ':',
 'Andy',
 'Murray',
 ',',
 'Emma',
 'Raducanu',
 'and',
 'Jack',
 'Draper',
 'win',
 'to',
 'reach',
 'third',
 'round',
 'World',
 'Athletics',
 'Championships',
 ':',
 'GB',
 "'s",
 'Keely',
 'Hodgkinson',
 'narrowly',
 'misses',
 'out',
 'on',
 'gold',
 'in',
 'dramatic',
 '800m',
 'NHS',
 'crisis',
 ':',
 'The',
 'medics',
 'trying',
 'to',
 'fix',
 'the',
 'health',
 'service',
 'How',
 'did',
 'jet',
 'crash',
 'into',
 'a',
 'block',
 'of',
 'flats',
 'in',
 'Russia',
 '?',
 'Prince',
 'Harry',
 'and',
 'Meghan',
 ':',
 'Where',
 'do',
 'they',
 'get',
 'their',
 'money',
 '?',
 'Chelsea',
 '4-2',
 'Man',
 'Utd',
 ':',
 'Chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'WSL',
 'title',
 'Tory',
 'leadership',
 ':',
 'I',
 "'d",
 'rather',
 'lose',
 'doing',
 'right',
 'thing',
 ',',
 'says',
 'Sunak',
 'Omagh',
 'police',
 'shooting',
 ':',
 'Four',
 'men',
 'released',
 'over',
 'John',
 'Caldwell',
 'attack',
 'Northern',
 'Ireland',
 '1-0',
 'Italy',
 ':',
 'Sarah',
 'McFadden',
 'scores',
 'famous',
 'winner',
 'in',
 'Belfast',
 'Actress',
 'Clara',
 'Darcy',
 ':',
 'Why',
 'I',
 "'m",
 'starring',
 'in',
 'a',
 'play',
 'about',
 'my',
 'brain',
 'tumour',
 'Bridgerton',
 ':',
 'South',
 'Asian',
 'faces',
 'on',
 'TV',
 "'makes",
 'me',
 'happy',
 "'",
 'Prince',
 'Harry',
 'remembers',
 'Queen',
 'Elizabeth',
 'II',
 "'s",
 'infectious',
 'smile',
 'Millions',
 'to',
 'receive',
 'latest',
 'cost-of-living',
 'payment',
 'Joe',
 'Biden',
 'heads',
 'to',
 'Middle',
 'East',
 'amid',
 'faltering',
 'US',
 'sway',
 'NHS',
 ':',
 'Public',
 'satisfaction',
 'with',
 'health',
 'service',
 'drops',
 'to',
 'record',
 'low',
 'Why',
 'have',
 "n't",
 'we',
 'seen',
 'any',
 'major',
 'winter',
 'storms',
 '?',
 'The',
 'Papers',
 ':',
 'Lions',
 "'bare",
 'teeth',
 "'",
 'and',
 'Starmer',
 "'s",
 'migration',
 'policy',
 'Afghanistan',
 'pupils',
 'in',
 'fear',
 'after',
 'spate',
 'of',
 'Islamic',
 'State',
 'attacks',
 'Princess',
 'of',
 'Wales',
 'Kate',
 'pays',
 'tribute',
 'to',
 'Queen',
 'Elizabeth',
 'at',
 'carol',
 'service',
 'Emma',
 'Raducanu',
 ...]

In [14]:
tokens_clean_lst

['refuse',
 'work',
 'liz',
 'truss',
 'brief',
 'world',
 'reacts',
 'uk',
 'political',
 'turmoil',
 'rationing',
 'energy',
 'nothing',
 'new',
 'offgrid',
 'community',
 'hunt',
 'superyachts',
 'sanctioned',
 'russian',
 'oligarch',
 'platinum',
 'jubilee',
 '70',
 'year',
 'queen',
 '70',
 'second',
 'red',
 'bull',
 'found',
 'guilty',
 'breaking',
 'formula',
 '1',
 'budget',
 'cap',
 'world',
 'triathlon',
 'championship',
 'series',
 'flora',
 'duffy',
 'beat',
 'georgia',
 'taylorbrown',
 'womens',
 'title',
 'terry',
 'hall',
 'coventry',
 'scooter',
 'rideout',
 'pay',
 'tribute',
 'singer',
 'post',
 'office',
 'fujitsu',
 'face',
 'inquiry',
 'horizon',
 'scandal',
 'pavement',
 'parking',
 'frightens',
 'me',
 'uk',
 'interest',
 'rate',
 'rise',
 'affect',
 'high',
 'could',
 'go',
 'stayed',
 'storm',
 'happens',
 'now',
 'six',
 'nation',
 'scotland',
 'best',
 'since',
 '99',
 'beat',
 'best',
 'ireland',
 'ever',
 'long',
 'liz',
 'truss',
 'survive',
 'prime',
 'minister',
 'platinum',
 'jubilee',
 'beacon',
 'light',
 'across',
 'globe',
 'celebrate',
 'queen',
 'reign',
 'top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 '5',
 'england',
 'russian',
 'said',
 'theyd',
 'take',
 'baby',
 'medic',
 'story',
 'week',
 'picture',
 '1117',
 'june',
 '2022',
 'xi',
 'jinping',
 'hong',
 'kong',
 'tight',
 'security',
 'city',
 'mark',
 '25',
 'year',
 'handover',
 'rescue',
 'carried',
 'silence',
 'listen',
 'sound',
 'life',
 'nick',
 'pope',
 'newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'china',
 'plan',
 'become',
 'next',
 'big',
 'space',
 'power',
 'barcelona',
 'thrash',
 'leader',
 'real',
 'madrid',
 'famous',
 'clasico',
 'win',
 'kuenssberg',
 'budget',
 'can',
 'not',
 'mask',
 'big',
 'change',
 'economy',
 'nicola',
 'bulley',
 'search',
 'know',
 'disappearance',
 'cost',
 'living',
 'christmas',
 'light',
 'display',
 'survive',
 'energy',
 'crisis',
 '100yearold',
 'edinburgh',
 'man',
 'still',
 'working',
 'three',
 'day',
 'week',
 'freya',
 '600kg',
 'walrus',
 'cause',
 'stir',
 'norway',
 'offer',
 'uk',
 'home',
 'ukrainian',
 'refugee',
 'nicola',
 'bulley',
 'search',
 'former',
 'police',
 'bos',
 'say',
 'criticism',
 'unfair',
 'bolduc',
 'democrat',
 'elevated',
 'republican',
 'backfire',
 'strike',
 'action',
 'cancelled',
 'queen',
 'death',
 'neighbourhood',
 'leading',
 'green',
 'energy',
 'revolution',
 'men',
 'u17',
 'european',
 'championship',
 'dutch',
 '17yearold',
 'isaac',
 'babadi',
 'score',
 'panenka',
 'penalty',
 'amtrak',
 'derailment',
 'three',
 'killed',
 'missouri',
 'train',
 'hit',
 'truck',
 'energy',
 'price',
 'cap',
 'rising',
 'bill',
 'four',
 'discount',
 'payment',
 'could',
 'help',
 'environment',
 'mushroom',
 'board',
 'future',
 'surfing',
 'flying',
 'boat',
 'tech',
 'cleaner',
 'shipping',
 'scottish',
 'football',
 'ban',
 'heading',
 'day',
 'match',
 'chris',
 'eubank',
 'jr',
 'v',
 'liam',
 'smith',
 'next',
 'boxing',
 'unacceptable',
 'taunt',
 'town',
 'destroyed',
 'make',
 'way',
 'whitesonly',
 'suburb',
 'ukraine',
 'war',
 'village',
 'celebrates',
 'russian',
 'retreat',
 'root',
 'hit',
 'ton',
 'england',
 'take',
 'command',
 'west',
 'indie',
 'heineken',
 'champion',
 'cup',
 'leicester',
 '166',
 'edinburgh',
 'jasper',
 'wiese',
 'try',
 'sends',
 'tiger',
 'last',
 'eight',
 'world',
 'cup',
 '2022',
 'bellingham',
 'gakpo',
 'fernandez',
 'breakout',
 'star',
 'briton',
 'jack',
 'fenton',
 'killed',
 'greek',
 'helicopter',
 'accident',
 'emotional',
 'sue',
 'barker',
 'get',
 'centre',
 'court',
 'ovation',
 'ukrainian',
 'skating',
 'sister',
 'back',
 'doing',
 'love',
 'england',
 'v',
 'india',
 'edgbaston',
 'official',
 'investigate',
 'crowd',
 'racism',
 'test',
 'newspaper',
 'headline',
 'rwanda',
 'plan',
 'will',
 'fail',
 'sa',
 'train',
 'kyiv',
 'force',
 'name',
 'leon',
 'sir',
 'lenny',
 'henry',
 'brings',
 'moving',
 'adoption',
 'story',
 'screen',
 'big',
 'brother',
 'star',
 'glyn',
 'wise',
 'plan',
 'priest',
 'minister',
 'asleep',
 'wheel',
 'dentist',
 'shortage',
 'say',
 'lib',
 'dems',
 'chris',
 'kaba',
 'met',
 'suspends',
 'officer',
 'shot',
 'dead',
 'unarmed',
 'man',
 'world',
 'cup',
 '2022',
 'learned',
 'group',
 'stage',
 'saw',
 'record',
 'number',
 'upset',
 'james',
 'webb',
 'nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'picture',
 'constitution',
 'hill',
 'cheltenham',
 'champion',
 'hurdle',
 'winner',
 'the',
 'horse',
 'generation',
 'least',
 'one',
 'victim',
 'could',
 'survived',
 'arena',
 'bomb',
 'inquiry',
 'gareth',
 'bale',
 'wale',
 'captain',
 'retires',
 'football',
 'aged',
 '33',
 'ukraine',
 'war',
 'silent',
 'street',
 'wiped',
 'donetsk',
 'town',
 'world',
 'cup',
 '2022',
 'vittorio',
 'pozzos',
 'legacy',
 'record',
 'might',
 'finally',
 'threat',
 'train',
 'strike',
 'worker',
 'vote',
 'six',
 'month',
 'walkout',
 'eidevall',
 '100',
 'sure',
 'arsenal',
 'advance',
 'firstleg',
 'draw',
 'ukraine',
 'war',
 'returning',
 'place',
 'father',
 'killed',
 'furniture',
 'firm',
 'made',
 'collapse',
 'customer',
 'dark',
 'refund',
 'widow',
 'u',
 'capitol',
 'riot',
 'officer',
 'stigma',
 'death',
 'nh',
 'reach',
 'deal',
 'lifesaving',
 'breastcancer',
 'drug',
 'giant',
 'ceramic',
 'sculpture',
 'sandy',
 'brown',
 'unveiled',
 'cornwall',
 'ceo',
 'secret',
 'one',
 'company',
 'attracts',
 'men',
 'boris',
 'becker',
 'tennis',
 'superstar',
 'crashed',
 'earth',
 'turkish',
 'mine',
 'explosion',
 'kill',
 '25',
 'leaf',
 'dozen',
 'trapped',
 'indian',
 'well',
 'andy',
 'murray',
 'emma',
 'raducanu',
 'jack',
 'draper',
 'win',
 'reach',
 'third',
 'round',
 'world',
 'athletics',
 'championship',
 'gb',
 'keely',
 'hodgkinson',
 'narrowly',
 'miss',
 'gold',
 'dramatic',
 '800m',
 'nh',
 'crisis',
 'medic',
 'trying',
 'fix',
 'health',
 'service',
 'jet',
 'crash',
 'block',
 'flat',
 'russia',
 'prince',
 'harry',
 'meghan',
 'get',
 'money',
 'chelsea',
 '42',
 'man',
 'utd',
 'chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'wsl',
 'title',
 'tory',
 'leadership',
 'rather',
 'lose',
 'right',
 'thing',
 'say',
 'sunak',
 'omagh',
 'police',
 'shooting',
 'four',
 'men',
 'released',
 'john',
 'caldwell',
 'attack',
 'northern',
 'ireland',
 '10',
 'italy',
 'sarah',
 'mcfadden',
 'score',
 'famous',
 'winner',
 'belfast',
 'actress',
 'clara',
 'darcy',
 'starring',
 'play',
 'brain',
 'tumour',
 'bridgerton',
 'south',
 'asian',
 'face',
 'tv',
 'make',
 'happy',
 'prince',
 'harry',
 'remembers',
 'queen',
 'elizabeth',
 'ii',
 'infectious',
 'smile',
 'million',
 'receive',
 'latest',
 'costofliving',
 'payment',
 'joe',
 'biden',
 'head',
 'middle',
 'east',
 'amid',
 'faltering',
 'u',
 'sway',
 'nh',
 'public',
 'satisfaction',
 'health',
 'service',
 'drop',
 'record',
 'low',
 'seen',
 'major',
 'winter',
 'storm',
 'paper',
 'lion',
 'bare',
 'teeth',
 'starmers',
 'migration',
 'policy',
 'afghanistan',
 'pupil',
 'fear',
 'spate',
 'islamic',
 'state',
 'attack',
 'princess',
 'wale',
 'kate',
 'pay',
 'tribute',
 'queen',
 'elizabeth',
 'carol',
 'service',
 'emma',
 'raducanu',
 'u',
 'open',
 'champion',
 'discusses',
 'tough',
 'split',
 'coach',
 'torben',
 'beltz',
 'oxford',
 'united',
 '03',
 'arsenal',
 'eddie',
 'nketiah',
 'score',
 'twice',
 'gunner',
 'progress',
 'ukraine',
 'roundup',
 'putin',
 'defends',
 'necessary',
 'invasion',
 'kyiv',
 'averts',
 'cyberattack',
 'ni',
 'protocol',
 'uk',
 'eu',
 'reach',
 'agreement',
 'trade',
 'data',
 'sharing',
 'super',
 'mario',
 'bros',
 'movie',
 'jack',
 'black',
 'rise',
 'game',
 'adaptation',
 'fourtime',
 'slam',
 'champion',
 'osaka',
 'announces',
 'pregnancy',
 'mcdonalds',
 'cocacola',
 'boycott',
 'call',
 'grow',
 'russia',
 'womens',
 'footballer',
 'year',
 'contender',
 'sam',
 'kerr',
 'war',
 'ukraine',
 'vladimir',
 'putin',
 'trained',
 'fighter',
 'africa',
 'ryanairs',
 'michael',
 'oleary',
 'want',
 'practical',
 'immigration',
 'approach',
 'i',
 'planned',
 'end',
 'life',
 '16',
 'still',
 'here',
 'england',
 '14',
 'men',
 'whipped',
 'twickenham',
 'crowd',
 'stirring',
 'display',
 'open',
 'rory',
 'mcilroy',
 'viktor',
 'hovland',
 'share',
 'lead',
 'st',
 'andrew',
 'third',
 'round',
 'real',
 'madrid',
 '20',
 'eintracht',
 'frankfurt',
 'karim',
 'benzema',
 'score',
 '324th',
 'goal',
 'real',
 'super',
 'cup',
 'win',
 'paper',
 'boris',
 'dossier',
 'judge',
 'to',
 'back',
 'down',
 'rwanda',
 'queen',
 'pull',
 'attending',
 'commonwealth',
 'service',
 'mosque',
 'fire',
 'suspect',
 'arrested',
 'second',
 'attack',
 'world',
 'cup',
 '2022',
 'belgium',
 'drop',
 'love',
 'away',
 'shirt',
 'qatar',
 'uk',
 'living',
 'covid',
 'plan',
 'soho',
 'street',
 'turned',
 'new',
 'london',
 'art',
 'gallery',
 'paper',
 'cruise',
 'ship',
 'house',
 'migrant',
 'new',
 'nh',
 'cash',
 'pay',
 'gap',
 'boss',
 'staff',
 'widen',
 'think',
 'tank',
 'local',
 'election',
 'child',
 'urge',
 'action',
 'save',
 'wildlife',
 'climate',
 'change',
 'uk',
 'track',
 'meet',
 'target',
 'trump',
 'investigation',
 'empty',
 'folder',
 'marked',
 'classified',
 'found',
 'maralago',
 'jim',
 'ratcliffe',
 'man',
 'bidding',
 'man',
 'utd',
 'shropshire',
 'baby',
 'death',
 'parent',
 'whose',
 'life',
 'changed',
 'forever',
 'bus',
 'journey',
 'taken',
 'since',
 '2',
 'fare',
 'cap',
 'say',
 'watchdog',
 'mexico',
 'kidnapping',
 'twisted',
 'moral',
 'code',
 'explains',
 'cartel',
 'apology',
 'rail',
 'fare',
 'england',
 'rise',
 'inflation',
 'rate',
 'minister',
 'say',
 'taliban',
 'school',
 'uturn',
 'a',
 'devastating',
 'day',
 'afghan',
 'girl',
 'malala',
 'yousafzai',
 'met',
 'police',
 'next',
 'force',
 'casey',
 'review',
 'ukraine',
 'war',
 'kherson',
 'mariupol',
 'key',
 'russian',
 'success',
 'heineken',
 'champion',
 'cup',
 'premiership',
 'cap',
 'hinders',
 'english',
 'team',
 'alex',
 'sanderson',
 'ukraine',
 'war',
 'protester',
 'expose',
 'crack',
 'kremlin',
 'war',
 'message',
 'liz',
 'truss',
 'vow',
 'match',
 'ukraine',
 'military',
 'support',
 'politics',
 'return',
 'wale',
 'population',
 'hit',
 'new',
 'high',
 'growth',
 'lowest',
 'many',
 'ukrainian',
 'fled',
 'home',
 'gone',
 'deloitte',
 'report',
 'european',
 'football',
 'made',
 'significant',
 'recovery',
 'covid',
 'pandemic',
 'nigeria',
 'flood',
 'overwhelming',
 'disaster',
 'leaf',
 '600',
 'people',
 'dead',
 'wimbledon',
 'emma',
 'raducanu',
 'andy',
 'murray',
 'set',
 'centre',
 'court',
 'day',
 'one',
 'journey',
 'site',
 'nord',
 ...]

### POS Tagging

In [15]:
nlp = spacy.load('en_core_web_sm')

In [16]:
# create a spacy doc from our raw text - better for pos tagging
# spacy_doc = nlp(' '.join(tokens_raw_lst))
spacy_doc = nlp(' '.join(tokens_clean_lst))

In [17]:
# extract the tokens and pos tags into a dataframe
pos_df = pd.DataFrame(columns=["tokens", "pos_tags"])
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'tokens': token.text, "pos_tags": token.pos_}])], ignore_index=True)
pos_df.head(20)

         tokens pos_tags
0        refuse      AUX
1          work     NOUN
2           liz    PROPN
3         truss      ADJ
4         brief      ADJ
5         world     NOUN
6        reacts     VERB
7            uk    PROPN
8     political      ADJ
9       turmoil     NOUN
10    rationing     VERB
11       energy     NOUN
12      nothing     PRON
13          new      ADJ
14      offgrid      ADJ
15    community     NOUN
16         hunt     NOUN
17  superyachts     NOUN
18   sanctioned     VERB
19      russian      ADJ

In [18]:
# token frequency count
pos_df_count = pos_df.groupby(["tokens", "pos_tags"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)
pos_df_count.head(15)

       tokens pos_tags  counts
30       2022      NUM      47
1162  england    PROPN      45
870       cup    PROPN      39
3056      say     VERB      37
3707       uk    PROPN      37
3840      war     NOUN      34
2386      new      ADJ      31
3948    world     NOUN      30
3949    world    PROPN      26
3710  ukraine    PROPN      23
3010  russian      ADJ      22
2136      man     NOUN      22
3711  ukraine     VERB      22
907       day     NOUN      21
3973     year     NOUN      20

In [19]:
pos_frequency = pos_df_count.groupby(["pos_tags"])["tokens"].count().sort_values(ascending=False)
pos_frequency.head(15)

pos_tags
NOUN     1390
PROPN    1303
VERB      632
ADJ       403
NUM        86
ADV        61
ADP        36
AUX        33
PRON       22
DET        10
SCONJ       7
INTJ        4
PART        4
X           3
Name: tokens, dtype: int64

In [20]:
# most common nouns
nouns = pos_df_count[pos_df_count.pos_tags == "NOUN"]
nouns.head(15)

        tokens pos_tags  counts
3840       war     NOUN      34
3948     world     NOUN      30
2136       man     NOUN      22
907        day     NOUN      21
3973      year     NOUN      20
1158    energy     NOUN      17
2847    record     NOUN      17
2657    police     NOUN      16
3870      week     NOUN      16
3935     woman     NOUN      16
1130  election     NOUN      16
811       cost     NOUN      16
3364    strike     NOUN      15
2629      plan     NOUN      14
2534     paper     NOUN      13

In [21]:
# most common verbs
verbs = pos_df_count[pos_df_count.pos_tags == "VERB"]
verbs.head(15)

       tokens pos_tags  counts
3056      say     VERB      37
3711  ukraine     VERB      22
1380    found     VERB      13
3461     take     VERB      13
1651      hit     VERB      13
358      beat     VERB      13
2133     make     VERB      13
1459      get     VERB      13
1473     give     VERB      11
3918      win     VERB      10
3136      set     VERB       8
1909   killed     VERB       8
2056   living     VERB       8
1482       go     VERB       7
1238     face     VERB       7

In [22]:
# most common adjectives
adjectives = pos_df_count[pos_df_count.pos_tags == "ADV"]
adjectives.head(15)

            tokens pos_tags  counts
311           back      ADV       8
3340         still      ADV       5
2322          much      ADV       4
177         almost      ADV       4
1379       forward      ADV       4
1085            dy      ADV       3
2838        really      ADV       3
303           away      ADV       3
1197          ever      ADV       3
2432           now      ADV       2
2385         never      ADV       2
1990         least      ADV       2
1882         keely      ADV       2
141          ahead      ADV       2
1729  indefinitely      ADV       2

In [23]:
from IPython.display import HTML, display
from spacy import displacy

In [24]:
def html_visiualizer(doc):
    html = displacy.render(doc, style="ent", jupyter=False)
    display(HTML(html))

### NER

In [25]:
# extract the tokens and entity tags into a dataframe
ner_df = pd.DataFrame(columns=["tokens", "labels"])
for token in spacy_doc.ents:
    ner_df = pd.concat([ner_df, pd.DataFrame.from_records([{"tokens": token.text, "labels": token.label_}])], ignore_index=True)

In [26]:
ner_df.head(10)

                       tokens    labels
0                     russian      NORP
1                     70 year      DATE
2                   70 second      TIME
3                        bull       ORG
4                           1  CARDINAL
5  georgia taylorbrown womens       ORG
6                  terry hall    PERSON
7                         six  CARDINAL
8                          99  CARDINAL
9              jubilee beacon    PERSON

In [27]:
# token frequency count
ner_df_counts = ner_df.groupby(["tokens", "labels"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)
ner_df_counts.head(5)

      tokens    labels  counts
34      2022  CARDINAL      30
451  russian      NORP      25
223    first   ORDINAL      15
35      2022      DATE      11
233   france       GPE      10

In [28]:
labels_frequency = ner_df_counts.groupby(["labels"])["tokens"].count().sort_values(ascending=False)
labels_frequency.head(15)

labels
PERSON      199
GPE          90
ORG          88
CARDINAL     72
DATE         63
NORP         37
TIME         11
LOC           7
FAC           6
ORDINAL       5
QUANTITY      3
PRODUCT       2
EVENT         1
PERCENT       1
Name: tokens, dtype: int64

In [29]:
# most common people
people = ner_df_counts[ner_df_counts.labels == "PERSON"]
people.head(15)

                tokens  labels  counts
432              putin  PERSON       7
127      boris johnson  PERSON       5
106      antonio conte  PERSON       3
102        andy murray  PERSON       3
524       tyre nichols  PERSON       2
581           zelensky  PERSON       2
249              harry  PERSON       2
254         hodgkinson  PERSON       2
252       harry meghan  PERSON       2
331        lenny henry  PERSON       2
292      john caldwell  PERSON       2
160              chris  PERSON       2
217                 eu  PERSON       2
120               beth  PERSON       2
584  zhou guanyu crash  PERSON       1

In [30]:
# most common places
places = ner_df_counts[ner_df_counts.labels == "LOC"]
places.head(15)

             tokens labels  counts
218          europe    LOC       2
174  crystal palace    LOC       1
91           africa    LOC       1
367     middle east    LOC       1
377   mount everest    LOC       1
401       north sea    LOC       1
564        west ham    LOC       1

In [31]:
html_visiualizer(spacy_doc)